### ISSUE TITLE
font display issue

### ISSUE THREAD

**Issue by sainiaj** [cowboysdude/MMM-History#1]
hi i love your module very useful and informational,

However can you make it so it is the same style font and looks like other modules at the moment its is completely different and does not blend it nicely 

Thank you and keep up the awesome work

**Comment by cowboysdude** [comment]
Sorry I missed this! I will look at the code later today.  I generally use a css file because some want to change things.  I can add the MM fonts to the mix if that will help! Thank you for your input and I will fix this for you!

**Comment by sainiaj** [comment]
Thanks you cowboy dude
I really appreciate,

I love the whole concept of your module very informative and good

And also if you can make it same font size pixel font face and align in
centre lol, I wish I knew how to do it myself


Thanks a lot

**Comment by cowboysdude** [comment]
You're welcome, I updated it to use MM fonts and the white color.  The entire module is centered :)
But still have the ability to use custom.css so other users can change fonts and colors as they like.
Let me know if that works for you!

**Comment by sainiaj** [comment]
cowboysdude 

the module is still in the bottom left corner 
and it says undefined  and cannot see any history :(

**Comment by sainiaj** [comment]
Hi I am still get the same error undefined and in bottom left corner 
Position is bottom.bar

**Comment by cowboysdude** [comment]
Can you post your config.js so I can see it?

**Comment by sainiaj** [comment]
{
         module: 'MMM-History',
        position: 'bottom_bar',
        config: {
        maxWidth: "300px"
        }
     },

**Comment by cowboysdude** [comment]
I updated the history.css file try a git pull and update to see if that helps.  Not sure what the issue really is because there's nothing in the module that puts it in the bottom left ... something else is pushing it there.
