### ISSUE TITLE
Address modification

### ISSUE THREAD

**Issue by ireeus** [cowboysdude/MMM-History#11]
At the moment the app has an address in MMM-History.js which doesn't allow to modify it through MMM-Remote-Control. There is Polish website which provides historical info in Polish language (https://historykon.pl/feed/ ). Can the address be moved to config file to make it easy to change please?

**Comment by cowboysdude** [comment]
I will look at it    :)

**Comment by cowboysdude** [comment]
Not sure what 'address' you are referring to.  This really isn't an issue it's a feature request.  ;)

This url comes back as invalid -> https://historykon.pl/feed/

You cannot simply move it to the config file because if the variables aren't the exact same the module will not work.

**Comment by ireeus** [comment]
It looks like the address is down but I was using it recently (at 17/06/2018 was OK). If the website comes back than the language support would be great. If no, then don't bother unless I'll find another service which provides such data. Thank you anyway for your replay.

**Comment by cowboysdude** [comment]
You're welcome
