### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by israel05** [cowboysdude/MMM-History#4]
It might be that the installation instructions are not clear or duplicated, but all i get is an "undefined" messages not any history fact.

**Comment by dherl0623** [comment]
It looks like this issue has been fixed as of yesterday! Do a `git pul`l to update it, then re-run `npm install`
Thanks to CowBoysDude for a great module!

**Comment by israel05** [comment]
Totally working right now! THANKS!

**Comment by sainiaj** [comment]
Hi it is working for me however, it is not aligning in the middle and font style and size is not same as rest of the other modules 

anyone else having the same issue 
![image](https://cloud.githubusercontent.com/assets/13112801/25601089/66dd0a38-2eb7-11e7-866e-812ab00e62ed.png)

config.js
{
         module: 'MMM-History',
        position: 'middle_center',
        config: {
        maxWidth: "300px"
        }
     },

**Comment by cowboysdude** [comment]
Not the same fonts because I used different fonts... as for the aligning what module position are you using?

**Comment by cowboysdude** [comment]
Not the same fonts because I used different fonts... as for the aligning what module position are you using?
Please come to the MM Forum to post issues... https://forum.magicmirror.builders/
