### ISSUE TITLE
Get info from non english wikipedia

### ISSUE THREAD

**Issue by jegerikke** [cowboysdude/MMM-History#7]
is there a way to get this to pull phrases from non english wiki "today in history"

in my case i like to get i from the norwegian site: https://no.m.wikipedia.org/wiki/Wikipedia:Dagen_i_dag

**Comment by cowboysdude** [comment]
I can look at later and let you know.

**Comment by cowboysdude** [comment]
I looked the info I get is an rss file...... it's not setup to scrap data
so now it won't work like that :)

**Comment by jegerikke** [comment]
any chanse its possibel to pull the lines from this page or make a rss feed of it to use?
http://m.nrk.no/dagenidag/

under you see the text holding info of the day:

![nrk dagen](https://user-images.githubusercontent.com/35518057/35137046-80924c8c-fce7-11e7-8ae1-0fe19637c8de.JPG)

**Comment by cowboysdude** [comment]
That is some good information.  The ONE thing I have never succeeded at is
page scraping.....I have never been able to get one to work......BUT what I
will do is ask a friend of mine to see if he's willing to help!!!  😀

Stay posted I'll let you know soon
